In [1]:
# In Anaconda Prompt, use 'conda install -c conda-forge dash' to install all the dash dependencies and libraries
# To install dash_bootstrap_components, use 'conda install -c conda-forge dash-bootstrap-components'
# For pip installation, use 'pip install dash' and 'pip install dash-bootstrap-components'

In [2]:
# Importing the required libraries
# Dash is a Python framework built on top of ReactJS, Plotly and Flask. It is used to create interactive web dashboards using just python
import dash                                         # Python framework for web-applications (main-backend)
from dash.dependencies import Input, Output         # For making the dashboard user-interactive to handle the input-output of the dashboard.        
import dash_core_components as dcc                  # For the components in the dashboard for user interaction like dropdowns, sliders, graphs in the dashboard         
import dash_html_components as html                 # For using HTML properties for frontend of dashboard
#import dash_daq as daq                             # I was importing this to improve the slider quality, but it didn't help much
import dash_bootstrap_components as dbc             # For using Bootstrap properties for presentation in frontend to get the layout theme of our dashboard.         
import plotly.io as pio                             # It is a low-level interface for displaying, reading and writing figures.         
pio.renderers.default = "browser"                   # To open a new tab in this default browser to deploy the dashboard         
import plotly.express as px                         # To plot the graph for deploying the plot on the dashboard        
import numpy as np                                  # To work with arrays        
import pandas as pd                                 # To work with Dataframes and tables
import math                                         # To perform mathematical calculations(like round-off)

In [3]:
# Importing the required dataset
# We are using encoding = 'mac_roman' because this dataset that was posted on Kaggle, was originally made in Mac-OS
df = pd.read_csv(r'C:\Users\Vipul\Downloads\WorldBankData.csv', encoding = 'mac_roman')

In [4]:
# Observing the first 5 rows of the dataset to see what all is available in the dataset. 
# We are doing this so that we get an idea of how do we have to play with the data to get the output we require.
df.head()

,Region,IncomeGroup,SpecialNotes,Country Name,1991,1992,1993,1994,1995,1996,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,South Asia,Low income,Fiscal year end: March 20; reporting period fo...,Afghanistan,1.300000,0.800000,0.700000,0.600000,1.800000,1.000000,...,8.20000,8.200000,8.100000,8.200000,8.000000,8.400000,8.600000,8.600000,8.60000,8.500000
1,Sub-Saharan Africa,Lower middle income,NaN,Angola,6.200000,6.100000,5.900000,6.200000,6.400000,6.400000,...,6.40000,6.200000,6.200000,6.200000,6.200000,6.200000,6.200000,6.200000,6.10000,6.200000
2,Europe & Central Asia,Upper middle income,NaN,Albania,12.700000,13.600000,15.000000,14.800000,14.300000,14.100000,...,13.00000,13.800000,14.200000,14.000000,13.400000,15.600000,17.500000,17.100000,15.20000,15.000000
3,NaN,NaN,Arab World aggregate. Arab World is composed o...,Arab World,12.569172,12.899079,13.596881,13.738961,14.560633,14.122322,...,10.29082,9.978365,9.963334,11.079206,11.358198,11.284136,11.376175,11.264614,11.24066,11.096682
4,Middle East & North Africa,High income,NaN,United Arab Emirates,3.200000,3.300000,3.300000,2.100000,1.800000,2.700000,...,4.00000,4.200000,4.100000,4.100000,4.100000,4.100000,4.000000,4.000000,3.80000,3.800000

In [5]:
# We remove the unnecessary column 'Special Notes' from the imported dataset. Because we are not using it. This is data-cleaning.
df.drop(['SpecialNotes'], inplace = True, axis = 1)
# Observing the first 5 rows of the dataset to see the change we made. 
df.head()

,Region,IncomeGroup,Country Name,1991,1992,1993,1994,1995,1996,1997,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,South Asia,Low income,Afghanistan,1.300000,0.800000,0.700000,0.600000,1.800000,1.000000,1.000000,...,8.20000,8.200000,8.100000,8.200000,8.000000,8.400000,8.600000,8.600000,8.60000,8.500000
1,Sub-Saharan Africa,Lower middle income,Angola,6.200000,6.100000,5.900000,6.200000,6.400000,6.400000,6.300000,...,6.40000,6.200000,6.200000,6.200000,6.200000,6.200000,6.200000,6.200000,6.10000,6.200000
2,Europe & Central Asia,Upper middle income,Albania,12.700000,13.600000,15.000000,14.800000,14.300000,14.100000,13.200000,...,13.00000,13.800000,14.200000,14.000000,13.400000,15.600000,17.500000,17.100000,15.20000,15.000000
3,NaN,NaN,Arab World,12.569172,12.899079,13.596881,13.738961,14.560633,14.122322,13.588103,...,10.29082,9.978365,9.963334,11.079206,11.358198,11.284136,11.376175,11.264614,11.24066,11.096682
4,Middle East & North Africa,High income,United Arab Emirates,3.200000,3.300000,3.300000,2.100000,1.800000,2.700000,2.600000,...,4.00000,4.200000,4.100000,4.100000,4.100000,4.100000,4.000000,4.000000,3.80000,3.800000

In [6]:
# To get a rough idea of how the values in the dataset are varying, observing minimum, maximum and mean values
df.describe()

,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
count,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,...,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000,232.000000
mean,8.737491,8.913977,9.146993,9.206319,9.148745,9.303947,9.208476,9.215979,9.171891,9.090720,...,7.936294,8.709275,8.842239,8.830451,8.838084,8.813377,8.677316,8.535599,8.422237,8.350775
std,6.008863,5.988098,6.137088,6.053356,6.118809,6.211707,6.133445,5.960125,5.770467,5.978851,...,5.577860,5.653687,5.827631,5.855038,6.057424,6.055662,5.994918,5.894127,5.839692,5.768752
min,0.100000,0.500000,0.400000,0.400000,0.200000,0.300000,0.700000,0.500000,0.300000,0.700000,...,0.300000,0.200000,0.400000,0.200000,0.200000,0.300000,0.100000,0.100000,0.200000,0.300000
25%,4.675000,4.925000,4.975000,5.075000,5.200000,5.375000,5.378766,5.300000,5.588005,4.875000,...,4.750000,5.400000,5.200000,5.000000,5.000000,5.049143,5.062712,5.000000,4.800000,4.875000
50%,6.900000,7.500000,7.700000,7.713781,7.515185,7.650000,7.700000,7.700000,7.650000,7.450000,...,6.400000,7.700000,7.590371,7.200000,7.114607,7.100000,6.729784,6.800000,6.500000,6.409962
75%,11.801523,11.976021,12.200000,12.350000,11.920385,12.398784,12.150000,12.225000,12.221660,12.409416,...,9.453536,10.125000,10.800000,11.225000,11.373848,11.525000,11.094356,10.809363,10.825000,10.955534
max,31.700001,31.400000,32.000000,31.799999,34.900002,37.000000,39.299999,34.500000,32.400002,32.900002,...,33.799999,32.200001,32.000000,31.400000,31.000000,31.100000,31.200001,31.299999,31.400000,31.400000

In [7]:
# This is a function to manipulate and return the dataset in the form required by us to perform visualization and other operations
# We are using a 'gap' variable here as a window. This can be used by the user to smoothen the curve in the plot through the Slider
# Default values for country and gap are 'India' and 1. They can be changed by the user as per their preferences through the Dropdown and the Slider.
# 'data' is the dataset to be used. In this project, dataset to be used is stored in 'df'.
def get_data(data, country = 'India', gap = 1):
    df1 = data.T[2:]                             # To transpose the dataset(T) and then remove the first 2 rows i.e indirectly removing the first 2 columns of the original dataset
    df1.reset_index()                            # To reset the index of the dataframe
    df2 = df1.T                                  # To transpose again
    
    # Now we will select the row where the Country Name is same as the input given by the user. 
    # Then we will set the 'Country Name' column as the index to make the values accesible easily.
    # We transpose the dataframe again
    # We set the window as the gap value given as input by the user and and smoothening of the curve will be done on the basis of the mean of the values of that particular country
    
    df3 = df2[df2['Country Name'] == country].set_index('Country Name').T.rolling(window = gap).mean()
    val_list = df3[country].tolist()             # Converting the array of values(unemployment rates) of the country to a list
    
    return df3, val_list                         # Returning the dataframe and the list of values

get_data(df, 'China')                            # Checking the function by passing 'China' as the country

(Country Name  China
 1991            4.9
 1992            4.4
 1993            4.3
 1994            4.3
 1995            4.6
 1996            4.6
 1997            4.6
 1998            4.7
 1999            4.7
 2000            4.5
 2001            4.5
 2002            4.4
 2003            4.3
 2004            4.3
 2005            4.1
 2006            4.0
 2007            3.8
 2008            4.4
 2009            4.3
 2010            4.2
 2011            4.3
 2012            4.5
 2013            4.5
 2014            4.6
 2015            4.5
 2016            4.6
 2017            4.6,
 [4.900000095,
  4.400000095,
  4.300000191000001,
  4.3000001910000005,
  4.599999904999999,
  4.599999904999998,
  4.599999904999998,
  4.699999808999999,
  4.6999998089999995,
  4.5,
  4.5,
  4.400000094999999,
  4.300000191,
  4.3000001910000005,
  4.099999904999999,
  3.999999999999999,
  3.7999999519999985,
  4.400000094999999,
  4.300000191,
  4.1999998089999995,
  4.3000001910000005,
  4.5,
  4.5,
  4.599999905000001,
  4.500000000000001,
  4.599999905000001,
  4.5999999050000016])

In [8]:
# For using the stylesheets and themes inbuilt in the Bootstrap library
stylesheets = [dbc.themes.BOOTSTRAP]
app = dash.Dash(__name__, external_stylesheets = stylesheets)           
app.title = 'Global Unemployment'                                 # Setting the app title

In [9]:
# Declaring colours required for presentation
# '#111111' - Black, '#E6FFFF' - Aqua/Teal, '#7FDBFF' - Light Blue
colours = {'background':'#111111', 'bodyColor':'#E6FFFF', 'text':'#7FDBFF', 'info':'#B30000'}

main_info = ''' Unemployment occurs when a person who is actively searching for employment is unable to find work. Unemployment is often used as a measure of the health of the economy.
Unemployment can have many sources like 
new technologies and inventions, the status of the economy which can be influenced by a recession, 
or competition caused by globalization and international trade, policies of the government, or regulation and market.

According to the UN's International Labour Organization (ILO), there were 172 million people worldwide (or 5% of the reported global workforce) without work in 2019.

The most frequent measure of unemployment is the unemployment rate, which is the number of unemployed people divided by the number of people in the labour force.\n
'''

# Defining the function which returns the Title of the Dashboard
# 'H1' is the biggest size possible for a Page Heading
def get_title():
    return html.H1(children = 'World Unemployment Rate Analysis',
                    style = {'textAlign':'center', 'color':colours['text']})

# Defining the function which returns the Caption(below the Title) of the Dashboard
def get_caption():
    return html.Div(children = 'Analysis of Global Unemployment Rate using the Data provided by the World Bank',
                    style = {'textAlign':'center', 'color':colours['text']})

# Combining for final display
def get_header():
    main_header =  dbc.Row([dbc.Col(get_title(), md = 12)], align = "center",
                            style = {'backgroundColor':colours['background']})
    
    # 'md'(or margin dimensions) = 12 indicates that on a 'medium' sized or larger screen each column/row should take up an 11th of the width/height.
    # It has been set randomly and can be changed as per the appearance preferred
    
    caption_header = dbc.Row([dbc.Col(get_caption(), md = 12)], align = "center",
                            style = {'backgroundColor':colours['background']})
    
    header = (main_header,caption_header)
    return header

# Defining the function which returns the main content (main-info) about the dashboard
def info():
    return html.H5(children = main_info, style = {'textAlign':'center', 'color':colours['info']})

# Defining the function which displays the main content in the dashboard
def get_info():
    content = dbc.Row([dbc.Col(info(), md = 12)], align = "center",)
                    
    return content

# Defining the function which returns the title for the Data Analytics section
def title2():
    return html.H1(children = 'Data Analysis',
                    style = {'textAlign':'center', 'color':colours['text']})

# Defining the function which displays the title "Data Analysis" 
def get_header2():
    return dbc.Row([dbc.Col(title2(), md = 12)], align = "center",
                            style = {'backgroundColor':colours['background']})

# Defining the function which returns the details of the inputs to be provided for the prediction
def pred_content():
    pred_data = ''' Select the Country and Year from the dropdowns to get the Unemployment Rate Prediction of 
    the selected Country in the selected Year.'''
    data_form = html.H5(children = pred_data, style = {'textAlign':'center', 'color':colours['info']})
    
    return dbc.Row([dbc.Col(data_form, md = 12)], align = "center",)
    
inc_content = ''' The Mean Unemployment Rate of a country gives us a rough estimate of the common value of its 
unemployment rate over the past years. Below you will find the graphical analysis of the Mean Unemployment Rates of countries 
depending on the category of Income they belong to. Four categories have been considered for Analysis: Low income, Lower middle income, 
Upper middle income and High income. This will help in analyzing the Unemployment Rate variation amongst the countries 
in the same Income group.'''

# Defining the function which returns the main content (inc_content) for the graphs for different income groups
def data_inc_content():
    return html.H5(children = inc_content, style = {'textAlign':'center', 'color':colours['info']})

# Defining the function which displays 'inc_content' for the graphs 
def get_inc_content():
    return dbc.Row([dbc.Col(data_inc_content(), md = 12)], align = "center",)

reg_content = ''' Given below is the graphical analysis of the Mean Unemployment Rates of countries 
depending on the Region they belong to. This will help in analyzing the Unemployment Rate variation amongst the countries 
in the same Region.'''

# Defining the function which returns content (reg_content) for the graph of countries in South Asia
def data_reg_content():
    return html.H5(children = reg_content, style = {'textAlign':'center', 'color':colours['info']})

# Defining the function which displays 'reg_content' for the graph
def get_reg_content():
    return dbc.Row([dbc.Col(data_reg_content(), md = 12)], align = "center",)

In [ ]:
a = {key1 : "val1", key2:"val2", key3:"val3"}
b = [1,2,3,4,5]
b[2]
a[key3]

arr = [1,2,3,4,5]
for i in arr:
    print(i)
    
    
dict = {'label':country1, 'value':country1}

dropdown = [{'Afghan':Afghan}, {'Angola':Angola}, ]

In [10]:
# This is a function to get the list of names of the countries in the dataset
def get_country_list():
    return df['Country Name'].unique()                              # Only unique values are listed and duplicate values are ignored.

# This is a function to sort the names of countries, storing it in a dictionary, and then appending it in a list(dropdown)
def create_dropdown(country_list):
    dropdown = []
    for cntry in sorted(country_list):
        temp_dict = {'label':cntry, 'value':cntry}
        dropdown.append(temp_dict)
    return dropdown

# Just for checking the above functions
create_dropdown(get_country_list())

# This is the function which makes and initialises the Dropdown using the core components in Dash
# When the dashboard will open, the default value in the dropdown will be 'India'
# 'id' are being used to refer and help call the particular functions they are defined in, when user gives inputs
# 'options' will show the list of countries the user can choose from
def get_dropdown():
    return html.Div([html.Label('Select Country'),
                    dcc.Dropdown(id = 'mydrop',
                    options = create_dropdown(get_country_list()), value = 'India'), 
                    html.Div(id = 'mydiv')])

In [11]:
# We will create a dropdown containing years from 2021-2030 i.e the period for which we will be calculating the predictions.
# The user can choose any year from 2021-2030 to find the predicted unemployment rate of that country in the given year.
# This is a function to get the years from 2021 to 2030, storing it in a dictionary, and then appending it in a list(dropdown3).
def create_dropdown3():
    val = list(range(2021, 2031))
    dropdown3 = []
    for yr in val:
        temp_dict3 = {'label':yr, 'value':yr}
        dropdown3.append(temp_dict3)
    return dropdown3

# This is a function which will display the dropdown of years from 2021-2030
# When the dashboard will open, the default value in the dropdown will be '2021'
# 'id' are being used to refer and help call the particular functions they are defined in, when user gives inputs
# 'options' will show the list of years the user can choose from
def get_dropdown3():
    return html.Div([html.Label('Select the Year for Prediction'),
                    dcc.Dropdown(id = 'mydrop3',
                    options = create_dropdown3(), value = 2021), 
                    html.Div(id = 'mydropd3')])

In [12]:
from sklearn.model_selection import train_test_split                            # To be able to split the dataset randomly into 2 sets i.e Testing set and Training set
from sklearn.linear_model import LinearRegression                               # To perform Linear Regression Algorithm on the Training set

# This is a function to manipulate and return the dataset in the form required by us to perform Linear Regression
def get_data_prediction(country = 'India'):
    # Now we will select the row where the Country Name is same as the input given by the user.
    # Then we will transpose the dataframe to remove the first 2 rows i.e removing the first 2 columns as they are unneccesary
    # Then we reset the index and transpose again
    # Then we set the first row (0) as the index and then we do the final transpose
    
    df_pred = df[df['Country Name'] == country].T[2:].reset_index().T.set_index(0).T
    
    # Now we rename the column 'Country Name' as 'Years', as this would make more sense as a column name
    # These changes are only reflected on the data we are currently working on. The original data, however will remain the same.
    # 'inplace' helps us decide whether we want the changes to affect what we are working on, or should the changes overwrite the original data
    df_pred.rename(columns = {'Country Name':'Years'}, inplace = True)
    return df_pred

In [13]:
# Just for checking the above functions
a = get_data_prediction('China')                                   # Storing the data returned in 'a'
X = a.iloc[:, :-1].values                                          # Assigning all the columns except the last one to 'X'
Y = a.iloc[:, 1].values                                            # Assigning the second column (i.e the last column in our case) to 'Y'
    
# We have decided to keep 80% of the original data as our Training set i.e the data on which our algorithm will work on make a prediction model depending on the variations in the values in that set.
# We keep the remaining 20% as our Test set i.e the data on which the above model will be tested to see hoe accurate or close it is to the original data
# 'train_test_split()' will do the splitting
# When 'random_state' set to an integer, train_test_split will return same results for each execution. when it is set to 'None', train_test_split will return different results for each execution.

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
model = LinearRegression()                                         # We call the function to start building the model
model.fit(X_train, Y_train)                                        # We fit the training data into the model
print(model.intercept_)                                            # Printing the intercept of the regression line
print(model.coef_)                                                 # Printing the slope of the regression line
y_pred = model.predict(X_test)                                     # Testing the model on our testing data(X_test)

# Now we get to see how close or accurate are the predicted values to the actual corresponding 'Y_test' values
l = pd.DataFrame({'Actual': Y_test, 'Predicted': y_pred})
l.T

18.348121657604207
[-0.00694031]

                 0       1        2        3        4        5
Actual         4.3     4.5      4.1      4.4      4.6      4.4
Predicted  4.51609  4.3634  4.43281  4.41199  4.49527  4.45363

In [14]:
from sklearn import metrics                 # To analyze the model error statistics using the inbuilt functions in this library
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, y_pred)))

Mean Absolute Error: 0.1426397296182952
Mean Squared Error: 0.03168374095991701
Root Mean Squared Error: 0.1779992723578302

In [15]:
# The following lines of codes are to determine the Accuracy of our prediction model
rmse = np.sqrt(metrics.mean_squared_error(Y_test, y_pred))
error = (rmse/Y_test.mean()) * 100
accuracy = 100 - error
print('Accuracy: ', accuracy)

Accuracy:  95.93918012779157

In [16]:
# Coming back to the project, this function is for buliding a model for prediction.
# It is no different from what we have done above already
# Only difference you will notice is that instead of testing the model on X_test set, now we are passing the value 'year' (2021 is the default year to to predict the unemployment rate)
# We have passed '[[year]]' because a 2D array was demanded. So 2D form of 'year' is [[year]]
# So whichever year is chosen by the user, that year will be passed to this function for prediction
# The dashboard will open showing the prediction for Unemployment rate in India for 2021 by default

def prediction(country = 'India', year = 2021):
    df_pred = get_data_prediction(country)
    X = df_pred.iloc[:, :-1].values
    Y = df_pred.iloc[:, 1].values

    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
    model = LinearRegression()
    model.fit(X_train, Y_train)
    y_pred = model.predict([[year]])
    return y_pred                                                      # Returning the prediction

# Just for checking the above function
prediction('United States')

array([6.96120853])

In [17]:
# This function calculates the accuracy of our prediction.
def calc_accuracy(country = 'India'):
    acc = prediction(country)                                # Storing the value of our prediction in 'acc'
    rmse = np.sqrt(metrics.mean_squared_error(Y_test, y_pred))             # Calculating the RMSE value
    error = (rmse/Y_test.mean()) * 100                                     # Calculating the error
    accuracy = 100 - error                                                 # Calculating the accuracy
    
    return accuracy                                                        # Returning the accuracy

# This function displays the accuracy of our predictions of the unemployment rates
def get_accuracy(country = 'India'):
    p = calc_accuracy(country)                                             # Accuracy is calculated and stored in 'p'
    
    # Now we display the accuracy
    accuracy_info = 'The accuracy of the unemployment rate prediction displayed above is close to {}%.'.format(math.floor(p))
    # We use math.floor() to round-off the accuracy percentage (to avoid never-ending decimals)
    
    # Format details to display
    data = html.H5(children = accuracy_info, style = {'textAlign':'center', 'color':colours['info']})
    disp = html.Div([dbc.Row([dbc.Col(data, md = 12)], align = "center",),], id = 'myacc')
                    
    return disp                                                           # Returns the accuracy percentage along with the format

In [18]:
# This function is for making a box in which we will show our prediction of unemployment rate in that particular country chosen by the user
# A value 'i' storing our prediction has been passed this function to print it
def box_format(i):
    # We make a dictionary containing the styles that will be required in the formatting
    head_style = {'textAlign':'center','fontSize':'200%'}
    body_style = {'textAlign':'center','fontSize':'150%'}
    heading = 'Unemployment Rate Prediction'                      # Setting the box-header  
    
    # Defining the header part of the box
    header = dbc.CardHeader(heading, style = head_style)
    
    # Defining the body part of the box
    body = dbc.CardBody(
        [html.H5('The Unemployment Rate is predicted to be around {}.'.format(round(i.tolist()[0], 2)), 
                 className = "mytext", style = body_style),])
    
    # Converting 'i' to a list and then displaying the first and only element to make the value look presentable.
    # We are giving a className to refer and help call the particular parts of code they are defined in
    
    # Combining the header and the body part
    box = [header,body]
    return box                                                   # Returning the box

In [19]:
# This function is using prediction() and box_format() to display a box with our specified contents in it
# Here we have also provided the details of how the box should look and where it should be positioned
def get_box(country = 'India', year = 2021):
    my_pred = prediction(country, year)                          # Calling the function to get the predicted unemployment rate for the input country in the input year
    
    # 'success' means 'green'
    # 'inverse' is generally set to True
    # We are setting the box size as 6 and offset(distance from the left-right edge of the screen) as 3
    card = html.Div([dbc.Row(
        [dbc.Col(dbc.Card(box_format(my_pred), color = 'success', inverse = True), 
                             md = dict(size = 6, offset = 3))], align = 'center', 
        className = 'mybox',),],
            id = 'mycard') 
    return card                                                  # Returning the box/card for display

In [20]:
# This is a function to set the format of the line-graph showing the curve of variation in umemployment rates
def get_plot(country = 'India', gap = 1):
    df3, val_list = get_data(df, country, gap)                   # Storing the values of a country returned by the function we defined above  

    if gap == 1:                                                 # Deciding the x-axis label 
        xaxis_head = 'Years'
    else:
        xaxis_head = '{}-Years Mean Average'.format(gap)         # Use of format() - Whatever value is stored in 'gap', it will automatically replace {}  
        # For example, if gap = 2, the x-axis label will read '2-Years Mean Average'
    
    # Now we put the required values in the line() function predefined in Plotly for a line graph
    # 'color_discrete_sequence' sets the colour of the line in the plot
    # 'title_x' is for aligning the graph title to the centre
    # 'bgcolor' means the background colour
    # The colours are assigned by their hexadecimal values. Like '#F2DFCE' is hexadecimal for a shade of pink 
    # 'update_layout' is used to store the additional details required for formatting of the plot
    
    fig = px.line(df3, y = val_list, x = df3.index, title = 'Yearly Unemployment Variations for {}'.format(country), width = 1550, height = 500, color_discrete_sequence = ['maroon'])
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = xaxis_head, yaxis_title = 'Unemployment Rate')
    
    # 'update_xaxes' is being used to set the appropriate scale for showing all the years on the x-axis
    # If not used, an interval of 5 years is set for the values on the x-axis
    
    fig.update_xaxes(nticks = len(df3.index))
    return fig                                                   # Returning the graph

In [21]:
# This is the function to call the function we had defined for the graph earlier.
# This is where the process of changing the graph as per user inputs will initiate
def show_plot():
    return dcc.Graph(id = 'myplot', figure = {})

In [22]:
# This function extracts the relevant data required to show plots of mean unemployment rates of countries on the basis of their Income Group and Region 
def get_data_analytics():
    df1 = df.T[1:]                              # To transpose the dataset(T) and then remove the first row i.e indirectly removing the first column of the original dataset
    df1.reset_index()                           # To reset the index of the dataframe  
    df2 = df1.T                                 # To transpose again
    return df2                                  # Returns the extracted data

In [23]:
# Now we will write the codes which plot the bar-graphs of mean unemployment rate of countries in the Income Groups - Low income, Lower middle income, Upper middle income, and High income
# If ma'am asks that why we wrote separate functions for each income group? Like why didn't we write just one function which will loop to every income group, and will display the respective graph one-by-one1/
# We will tell her that we tried it (because  I did, and it doesn't work). When we loop in the Income group, at the end it only returns the graph for the last element in the group i.e High income.
# So instead we wrote different functions for all groups

# This is a function which plots graph for 'Low income' Income group.
def get_li_plot():
    df2 = get_data_analytics()                                  # Extracting required data and storing it in df2
    df3 = df2[df2['IncomeGroup'] == 'Low income']               # Selecting those rows which have income group  as 'Low income' and storing them in df3
    d = df3.T[1:].T                                             # To get all the columns (Country Name and 1991-2017) in 'd' i.e removing the 'Income Group' column because we have alredy extracted 'low income' countries
    s = d.T[1:].T                                               # To remove 'Country Name' column, and storing in 's'. We do this because we now have to calculate the mean. So only numerical values should be there in the data.
    m = s.mean(axis = 1)                                        # Calculating the Mean. 'axis=1' means mean is being calculated along the rows. Just F.Y.I, for calculating along the columns, axis=0
    combined = pd.concat([d['Country Name'], m], axis = 1)      # Combining the 'Country Name' column and mean unemployment rates 'm', into a dataframe.
    combined.columns =['Country Name', 'Mean']                  # So there are 2 columns in our new dataframe. We rename the columns to 'Country Name' and 'Mean'
        
    # To draw a bar-graph, we use px.bar(), a pre-defined function in Plotly for bar-graph
    # Below we use 'barmode = 'group'' because there are many types of bar graphs, like stacked, multiple, nomal etc. So we wanted to use normal bargraph for which barmode is assigned 'group'
    # The remaining details are same as that of line-graph
    
    fig = px.bar(combined, x = 'Country Name', y = 'Mean', title = 'Average Unemployment Rates of the Countries having Low income', width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Countries having Low income', yaxis_title = 'Unemployment Rates')
    return dcc.Graph(id = 'plot1', figure = fig)

In [24]:
# This is a function which plots graph for 'Lower middle income' Income group.
def get_lmi_plot():
    df2 = get_data_analytics()
    df3 = df2[df2['IncomeGroup'] == 'Lower middle income']
    d = df3.T[1:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined = pd.concat([d['Country Name'], m], axis = 1)
    combined.columns =['Country Name', 'Mean']
        
    fig = px.bar(combined, x = 'Country Name', y = 'Mean', title = 'Average Unemployment Rates of the Countries having Lower middle income', width = 1550, height = 500, barmode = 'group', color_discrete_sequence = ['green'])
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#FFFFB3', paper_bgcolor = '#FFFFB3', xaxis_title = 'Countries having Lower middle income', yaxis_title = 'Unemployment Rates')
    return dcc.Graph(id = 'plot2', figure = fig)

In [25]:
# This is a function which plots graph for 'Upper middle income' Income group.
def get_umi_plot():
    df2 = get_data_analytics()
    df3 = df2[df2['IncomeGroup'] == 'Upper middle income']
    d = df3.T[1:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined = pd.concat([d['Country Name'], m], axis = 1)
    combined.columns =['Country Name', 'Mean']
        
    fig = px.bar(combined, x = 'Country Name', y = 'Mean', title = 'Average Unemployment Rates of the Countries having Upper middle income', width = 1550, height = 500, barmode = 'group', color_discrete_sequence = ['yellow'])
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#FFCCCC', paper_bgcolor = '#FFCCCC', xaxis_title = 'Countries having Upper middle income', yaxis_title = 'Unemployment Rates')
    return dcc.Graph(id = 'plot3', figure = fig)

In [26]:
# This is a function which plots graph for 'High income' Income group.
def get_hi_plot():
    df2 = get_data_analytics()
    df3 = df2[df2['IncomeGroup'] == 'High income']
    d = df3.T[1:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined = pd.concat([d['Country Name'], m], axis = 1)
    combined.columns =['Country Name', 'Mean']
        
    fig = px.bar(combined, x = 'Country Name', y = 'Mean', title = 'Average Unemployment Rates of the Countries having High income', width = 1550, height = 500, barmode = 'group', color_discrete_sequence = ['red'])
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#CCFFCC', paper_bgcolor = '#CCFFCC', xaxis_title = 'Countries having High income', yaxis_title = 'Unemployment Rates')
    return dcc.Graph(id = 'plot4', figure = fig)

In [27]:
# Now we will write the codes which plot the bar-graphs of mean unemployment rate of countries in different Regions - South Asia, Sub-Saharan Africa, Middle East & North Africa, North America, Latin America & Caribbean, Europe & Central Asia, and East Asia & Pacific 
# If ma'am asks why did you write different functions for each Region, so it is the same reason as for Income Group
# If ma'am asks that you have written the code for all Regions, but in the dashboard you have displayed graph for just one region? Why?
# So we will tell her that ma'am we wrote the code, and when we tried executing all of them together, there was an Internal Server Error 500 due to overload in the the page.
# We have executed all the functions individually and all work fine, so we chose to show all the Income Group graphs, and only 1 Region graph to prevent overloading

# This is a function which plots graph for 'South Asia' Region
def get_sa_plot():
    df1 = df
    df1 = df1.reset_index()                                           # To reset the index of the dataframe
    df3 = df1[df1['Region'] == 'South Asia']                          # Extracting rows which have Region as 'South Asia' adn storing them in df3
    d = df3.T[3:].T                                                   # Remaining all steps are same as seen in Income Group graphs
    s = d.T[1:].T                                                     
    m = s.mean(axis = 1)
    combined2 = pd.concat([d['Country Name'], m], axis = 1)
    combined2.columns =['Country Name', 'Mean']
    
    # This time we plot a horizontal bar graph
    # Earlier we plotted Country Names on the s-axis and Mean on y-axis for a verticsl bar-graph.
    # All we have to do now is that we plot the Mean on x-axis and the Country names on the y-axis. This plots a horizontal graph.
    fig = px.bar(combined2, x = 'Mean', y = 'Country Name', title = 'Average Unemployment Rates of the Countries in South Asia', width = 1550, height = 500, barmode = 'group', color_discrete_sequence = ['orange'])
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Unemployment Rates', yaxis_title = 'Countries in South Asia')
    return dcc.Graph(id = 'plot5', figure = fig)

In [28]:
# This is a function which plots graph for 'Sub-Saharan Asia' Region
def get_ssa_plot():
    df1 = df
    df1 = df1.reset_index()
    df3 = df1[df1['Region'] == 'Sub-Saharan Africa']
    d = df3.T[3:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined2 = pd.concat([d['Country Name'], m], axis = 1)
    combined2.columns =['Country Name', 'Mean']
    
    fig = px.bar(combined2, x = 'Mean', y = 'Country Name', title = 'Average Unemployment Rates of the Countries in Sub-Saharan Africa', width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Unemployment Rates', yaxis_title = 'Countries in Sub-Saharan Africa')
    return dcc.Graph(id = 'plot5', figure = fig)

In [29]:
# This is a function which plots graph for 'Middle East & North Africa' Region
def get_mena_plot():
    df1 = df
    df1 = df1.reset_index()
    df3 = df1[df1['Region'] == 'Middle East & North Africa']
    d = df3.T[3:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined2 = pd.concat([d['Country Name'], m], axis = 1)
    combined2.columns =['Country Name', 'Mean']
    
    fig = px.bar(combined2, x = 'Mean', y = 'Country Name', title = 'Average Unemployment Rates of the Countries in Middle East & North Africa', width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Unemployment Rates', yaxis_title = 'Countries in Middle East & North Africa')
    return dcc.Graph(id = 'plot5', figure = fig)

In [30]:
# This is a function which plots graph for 'North America' Region
def get_na_plot():
    df1 = df
    df1 = df1.reset_index()
    df3 = df1[df1['Region'] == 'North America']
    d = df3.T[3:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined2 = pd.concat([d['Country Name'], m], axis = 1)
    combined2.columns =['Country Name', 'Mean']
    
    fig = px.bar(combined2, x = 'Mean', y = 'Country Name', title = 'Average Unemployment Rates of the Countries in North America', width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Unemployment Rates', yaxis_title = 'Countries in North America')
    return dcc.Graph(id = 'plot5', figure = fig)

In [31]:
# This is a function which plots graph for 'Latin America and Carribean' Region
def get_lac_plot():
    df1 = df
    df1 = df1.reset_index()
    df3 = df1[df1['Region'] == 'Latin America & Caribbean']
    d = df3.T[3:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined2 = pd.concat([d['Country Name'], m], axis = 1)
    combined2.columns =['Country Name', 'Mean']
    
    fig = px.bar(combined2, x = 'Mean', y = 'Country Name', title = 'Average Unemployment Rates of the Countries in Latin America & Caribbean', width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Unemployment Rates', yaxis_title = 'Countries in Latin America & Caribbean')
    return dcc.Graph(id = 'plot5', figure = fig)

In [32]:
# This is a function which plots graph for 'Europe & Central Asia' Region
def get_eca_plot():
    df1 = df
    df1 = df1.reset_index()
    df3 = df1[df1['Region'] == 'Europe & Central Asia']
    d = df3.T[3:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined2 = pd.concat([d['Country Name'], m], axis = 1)
    combined2.columns =['Country Name', 'Mean']
    
    fig = px.bar(combined2, x = 'Mean', y = 'Country Name', title = 'Average Unemployment Rates of the Countries in Europe & Central Asia', width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Unemployment Rates', yaxis_title = 'Countries in Europe & Central Asia')
    return dcc.Graph(id = 'plot5', figure = fig)

In [33]:
# This is a function which plots graph for 'East Asia & Pacific' Region
def get_eap_plot():
    df1 = df
    df1 = df1.reset_index()
    df3 = df1[df1['Region'] == 'East Asia & Pacific']
    d = df3.T[3:].T
    s = d.T[1:].T
    m = s.mean(axis = 1)
    combined2 = pd.concat([d['Country Name'], m], axis = 1)
    combined2.columns =['Country Name', 'Mean']
    
    fig = px.bar(combined2, x = 'Mean', y = 'Country Name', title = 'Average Unemployment Rates of the Countries in East Asia & Pacific', width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Unemployment Rates', yaxis_title = 'Countries in East Asia & Pacific')
    return dcc.Graph(id = 'plot5', figure = fig)

In [34]:
# This is the function to create and return the slider for users to change the interval between the years for the plot
# Minimum and Maximum values have been set for the Slider
# 'step' decides the incremental value
# 'marks' is a dictionary of values that will be shown on the slider, and functions just like a normal dictionary in Python
# 'value' is the initial value on the Slider
def create_slider():
    return html.Div([dcc.Slider(id = 'myslider', min = 1, max = 10, step = 1,
                        marks = {1:'1', 3:'3', 5:'5', 7:'7', 9:'9'}, value = 1),
                        html.Div([html.Label('Select Gap Intervals')], id = 'mydiv2' + str(id), style = {'textAlign':'center'})])

In [35]:
# This function defines the information about the slider used and displays it.
def slider_data():
    slider_data = '''A Slider has been provided below the graph so that the gap interval can be varied to smoothen the curve. 
    However, this variation will not affect the prediction of the unemployment rate because the actual data will remain the same.'''
    
    a = html.H5(children = slider_data, style = {'textAlign':'center', 'color':colours['info']})
    b = dbc.Row([dbc.Col(a, md = 12)], align = "center",)
                    
    return b                                           # Returns the information along with the format

In [36]:
# TO BE IGNORED
def plot_analytics(inc, year):
    df2 = get_data_analytics()
    df3 = df2[df2['IncomeGroup'] == inc]
    d1 = df3.T[1:].T
    d2 = d1.T[1:].T
    rate_list = d2[year]
    
    fig = px.bar(d2, x = 'Country Name', y = year, title = 'Unemployment Rates in the year {}'.format(year), width = 1550, height = 500, barmode = 'group')
    fig.update_layout(title_x = 0.5, plot_bgcolor = '#F2DFCE', paper_bgcolor = '#F2DFCE', xaxis_title = 'Names of the Countries having {}'.format(inc), yaxis_title = 'Unemployment Rates')
    return fig

In [37]:
# TO BE IGNORED
def show_data():
    return dcc.Graph(id = 'plot', figure = {})

In [38]:
# TO BE IGNORED
def create_dropdown2():
    a = df['IncomeGroup'].unique()
    a = [x for x in a if not pd.isnull(x)]
    dropdown2 = []
    for inc in a:
        temp_dict2 = {'label':inc, 'value':inc}
        dropdown2.append(temp_dict2)
    return dropdown2

def get_dropdown2():
    return html.Div([html.Label('Select the Income Group'),
                    dcc.Dropdown(id = 'mydrop2',
                    options = create_dropdown2(), value = 'Low income'), 
                    html.Div(id = 'mydivdrop')])

In [39]:
# TO BE IGNORED
def create_slider2():
    x = df.T[3:].T
    return html.Div([dcc.Slider(id = 'myslider2', min = 1991, max = 2017, step = 1, 
                                marks={str(yr): str(yr) for yr in x.columns}, value = 1991),
                        html.Div([html.Label('Select the Year')], id = 'mydiv3' + str(id), style = {'textAlign':'center'})])

In [40]:
# This is a function to combine all the previous pieces of the functions to decide the whole layout of the dashboard i.e how will it be displayed to the user 
def get_layout():
    page_header = get_header()                      # For the Title and the Caption
    
    layout = dbc.Container(
        [page_header[0],                            # Title
            page_header[1],                         # Caption
            html.Hr(),                              # Leave a line - Hr() is the wrapper function for <hr> tag in HTML. It creates a horizontal rule break.
            get_info(),                             # Information
            html.Hr(),                              # Leave a line
            get_box(),                              # For the Prediction Box
            html.Hr(),                              # Leave a line
            pred_content(),                         # Details of the Inputs to be provided to the dropdowns
            get_accuracy(),                         # Accuracy Information
            html.Hr(),                              # Leave a line
            dbc.Row([dbc.Col(get_dropdown(), md = dict(size = 4, offset = 4))]),                   # For the Dropdown
         
            dbc.Row([dbc.Col(get_dropdown3(), md = dict(size = 4, offset = 4))]),                  # For the Dropdown
            html.Hr(),
         
            dbc.Row([dbc.Col(show_plot(), md = dict(size = 6, offset = 0))], align = "center"),     # For the line-graph
            html.Hr(),                              # Leave a line
         
            dbc.Row([dbc.Col(create_slider(), md = dict( size = 4, offset = 4))]),                  # For the Slider
            html.Hr(),
            slider_data(),                          # For the Slider information
            html.Hr(),
            html.Hr(),
            get_header2(),                          # For the Data Analytics section title
            html.Hr(),
            get_inc_content(),                      # For information related to the graphs on Income Groups
            html.Hr(),
            html.Hr(),
            dbc.Row([dbc.Col(get_li_plot(), md = dict(size = 6, offset = 0))], align = "center"),   # For the 'Low income' bar-graph
            html.Hr(),
            html.Hr(),
            dbc.Row([dbc.Col(get_lmi_plot(), md = dict(size = 6, offset = 0))], align = "center"),  # For the 'Lower middle income' bar-graph
            html.Hr(),
            html.Hr(),
            dbc.Row([dbc.Col(get_umi_plot(), md = dict(size = 6, offset = 0))], align = "center"),  # For the 'Upper middle income' bar-graph
            html.Hr(),
            html.Hr(),
            dbc.Row([dbc.Col(get_hi_plot(), md = dict(size = 6, offset = 0))], align = "center"),   # For the 'High income' bar-graph
            html.Hr(),
            html.Hr(),
            get_reg_content(),                     # For information related to graphs on Regions
            html.Hr(),
            html.Hr(),
            #dbc.Row([dbc.Col(get_ssa_plot(), md = dict(size = 6, offset = 0))], align = "center"),
            #html.Hr(),
            #dbc.Row([dbc.Col(get_mena_plot(), md = dict(size = 6, offset = 0))], align = "center"),
            #html.Hr(),
            #dbc.Row([dbc.Col(get_eca_plot(), md = dict(size = 6, offset = 0))], align = "center"),
            #html.Hr(),
            #dbc.Row([dbc.Col(get_eap_plot(), md = dict(size = 6, offset = 0))], align = "center"),
            #html.Hr(),
            dbc.Row([dbc.Col(get_sa_plot(), md = dict(size = 6, offset = 0))], align = "center"),  # For the 'South Asia' bar-graph
            #html.Hr(),
            #dbc.Row([dbc.Col(get_dropdown2(), md = dict(size = 4, offset = 4))]),
            #html.Hr(),
            #dbc.Row([dbc.Col(show_data(), md = dict(size = 6, offset = 0))], align = "center"),
            #html.Hr(),
            #dbc.Row([dbc.Col(create_slider2(), md = dict( size = 4, offset = 4))]),
            html.Hr()],                                                                        
        fluid = True, style = {'backgroundColor':colours['bodyColor']})                            # Some conventional layout details
    
    return layout                                   # Returning the final layout

In [41]:
app.layout = get_layout()                        # Assigning our final layout to the app/dashboard

In [42]:
# Now we come to the most crucial part of the project i.e the callbacks.
# Callbacks play a major role to make the application user interactive.
# Here we create two lists, one for the Output parts and one for the Input parts.
# Output list will consist of the elements that should change when a user gives or changes an input.
# Input list will consist of elements that will be used by the user to give or change inputs.
# In our case, the 2 DropdownS and the Slider are the Inputs and the Prediction Box and the Line-Graph are the Outputs.
# We also notice that there is a 'component_id' and a 'component_property' mentioned.
# The 'component_id' is the element which will be searched for in the program when inputs are changed and the corresponding output is desired
# The 'component_property' is the element in the 'id', in which the changes will take place.
# For example: Consider that we have given inputs (A country and a Year) to the Dropdowns and the Slider (Gap interval)
# First, it will find the id's from the Input list, i.e 'mydrop', 'mydrop3' and 'myslider' to see how these components function while taking an input
# Next, it will assign the inputs given to the 'component_property' mentioned in the callback (in this case, it is 'value')
# This will finalize the inputs.
# Now it will find the id's from the Output list, i.e 'myplot' and 'mycard' to see how these components function when given an input
# Next, it will find the 'component_property' mentioned in the callback (in this case, they are 'figure' and 'children')
# 'children' is a default 'component_property' when none are mentioned in the particular 'id'
# Then it will make the appropriate changes as per the inputs given and give the desired outputs
# This way, the Graph and the Prediction will keep on changing as per the inputs given to the Dropdowns and Slider by the user

@app.callback(
    [Output(component_id = 'myplot', component_property = 'figure'),          # Line-graph
    Output(component_id = 'mycard', component_property = 'children')],        # Prediction Box
    #Output(component_id = 'plot', component_property = 'figure')],      
    [Input(component_id = 'mydrop', component_property = 'value'),            # Dropdown for selecting Country
     Input(component_id = 'myslider', component_property = 'value'),          # Slider
     Input(component_id = 'mydrop3', component_property = 'value')])          # Dropdown for selecting Year
     #Input(component_id = 'mydrop3', component_property = 'value'),
     #Input(component_id = 'myslider2', component_property = 'value')])

# This update function must be defined after the callback
# This function in a way directs the callback to where to search the 'id' by returning the functions that affect the output.
# As you can see, three values have been passed to the function; 'input1' is the country name and 'input2' is the gap window, and 'input3' is the year selected for prediction
# On the basis of these inputs, the functions for the graph and prediction has been called and returned.
# 'get_box()' takes country name and the year as input, because the box displays the prediction for the country adn year selected. It has nothing to do with a gap window. It remains the same, no matter what the gap window is.
# And 'get_plot()', takes country name and the gap interval as the input, because it will display the graph of unemployment rates of the country. It has nothing to do with the year selected because it will not change the graph

def update_output(input1, input2, input3):
    return get_plot(input1, input2), get_box(input1, input3)

# TO BE IGNORED

@app.callback(
    [Output(component_id = 'plot', component_property = 'figure')],
    [Input(component_id = 'mydrop2', component_property = 'value')])          # Dropdown
     #Input(component_id = 'myslider2', component_property = 'value')])

def update_output(input4, input5):
    return plot_analytics(input4, input5)

In [43]:
# Running the Dashboard App server on the browser
# If running the dashboard on Jupyter Notebook, use debug = False. (Because it does not work when it is True)
# If running on a Text Editor or an IDE, use debug = True

if __name__ == '__main__':
    app.run_server(debug = False)
    #app.run_server(debug = True)

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [02/May/2021 13:33:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:33:33] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:33:33] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:33:34] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:33:46] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:33:52] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:33:55] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:34:00] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:34:04] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:34:07] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:34:10] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:34:16] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [02/May/2021 13:34:19] "POST /_dash-update-component HTTP/1.1" 200 -